# Generated by Django 4.2.30 on 2026-06-22 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='项目名称')),
                ('summary', models.CharField(max_length=300, verbose_name='摘要')),
                ('description', models.TextField(verbose_name='项目说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '进行中'), ('closed', '已关闭'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('starts_at', models.DateTimeField(verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='donation_projects', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '捐赠项目',
                'verbose_name_plural': '捐赠项目',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物资名称')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('required_quantity', models.PositiveIntegerField(verbose_name='需求数量')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='donations.donationproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '需求物资',
                'verbose_name_plural': '需求物资',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='认捐数量')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('status', models.CharField(choices=[('pledged', '待交付'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pledged', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='donations.donationitem', verbose_name='物资')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to=settings.AUTH_USER_MODEL, verbose_name='认捐人')),
            ],
            options={
                'verbose_name': '物资认捐',
                'verbose_name_plural': '物资认捐',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['item', 'status'], name='pledge_item_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='donationitem',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_donation_project_item'),
        ),
    ]
