# Generated by Django 4.2.30 on 2026-06-21 04:08

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.accounts.models.avatar_upload_to, verbose_name='头像'),
        ),
    ]
