# Generated by Django 4.2.30 on 2026-06-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='campuses.campus', verbose_name='所属校区'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='身份说明'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='学号/工号'),
        ),
    ]
