# Generated by Django 4.2.30 on 2026-06-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '标签分类',
                'verbose_name_plural': '标签分类',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(default='#66793a', max_length=20, verbose_name='颜色')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='tags.tagcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签内容',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_tag_category_name'),
        ),
    ]
