# Generated by Django 4.2.30 on 2026-06-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学校名称')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='学校地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校管理',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='校区名称')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='校区地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='campuses.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '校区',
                'verbose_name_plural': '校区管理',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_campus_school_name'),
        ),
    ]
