# Generated by Django 4.2.30 on 2026-06-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ 问题',
                'verbose_name_plural': 'FAQ 问题',
                'ordering': ('category', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('rescue', '救助信息'), ('adoption', '领养中心'), ('volunteer', '志愿者社区'), ('donation', '爱心捐赠'), ('activity', '校园活动')], max_length=20, verbose_name='所属模块')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': 'FAQ 分类',
                'verbose_name_plural': 'FAQ 分类',
                'ordering': ('module', 'sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='faqcategory',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='uniq_faq_module_category'),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faqs.faqcategory', verbose_name='分类'),
        ),
    ]
