# Generated by Django 4.2.30 on 2026-06-22 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(verbose_name='领养原因')),
                ('housing', models.CharField(max_length=255, verbose_name='居住条件')),
                ('experience', models.TextField(blank=True, verbose_name='养宠经验')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='审核状态')),
                ('pending_marker', models.BooleanField(default=True, editable=False, null=True)),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_applications', to='animals.animal', verbose_name='申请动物')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_adoption_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '领养申请',
                'verbose_name_plural': '领养申请',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdoptionRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '有效'), ('ended', '已终止'), ('cancelled', '已撤销')], default='active', max_length=20, verbose_name='关系状态')),
                ('active_marker', models.BooleanField(default=True, editable=False, null=True)),
                ('started_at', models.DateTimeField(verbose_name='领养开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='终止时间')),
                ('end_note', models.TextField(blank=True, verbose_name='终止说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_relationships', to=settings.AUTH_USER_MODEL, verbose_name='领养人')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_relationships', to='animals.animal', verbose_name='领养动物')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='relationship', to='adoptions.adoptionapplication', verbose_name='领养申请')),
            ],
            options={
                'verbose_name': '领养关系',
                'verbose_name_plural': '领养关系',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['adopter', 'status'], name='adoption_user_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='adoptionrelationship',
            constraint=models.UniqueConstraint(fields=('animal', 'active_marker'), name='uniq_active_adoption_animal'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['status', '-created_at'], name='adoption_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='adoptionapplication',
            constraint=models.UniqueConstraint(fields=('applicant', 'animal', 'pending_marker'), name='uniq_pending_adoption_user_animal'),
        ),
    ]
