# Generated by Django 4.2.30 on 2026-06-22 04:09

import apps.animals.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campuses', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='动物名称')),
                ('gender', models.CharField(choices=[('male', '公'), ('female', '母'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('estimated_age', models.CharField(blank=True, max_length=50, verbose_name='估算年龄')),
                ('health_status', models.CharField(choices=[('healthy', '健康'), ('injured', '受伤'), ('sick', '患病'), ('recovering', '康复中'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='健康状态')),
                ('rescue_status', models.CharField(choices=[('waiting', '待救助'), ('rescued', '已救助')], default='waiting', max_length=20, verbose_name='救助状态')),
                ('adoption_status', models.CharField(choices=[('unavailable', '暂不可领养'), ('available', '待领养'), ('adopted', '已领养')], default='unavailable', max_length=20, verbose_name='领养状态')),
                ('found_location', models.CharField(max_length=255, verbose_name='发现位置')),
                ('description', models.TextField(verbose_name='情况说明')),
                ('is_published', models.BooleanField(default=True, verbose_name='公开展示')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='campuses.campus', verbose_name='所属校区')),
            ],
            options={
                'verbose_name': '动物信息',
                'verbose_name_plural': '动物信息',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '动物分类',
                'verbose_name_plural': '动物分类',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RescueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(blank=True, max_length=80, verbose_name='动物名称')),
                ('gender', models.CharField(choices=[('male', '公'), ('female', '母'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('health_status', models.CharField(choices=[('healthy', '健康'), ('injured', '受伤'), ('sick', '患病'), ('recovering', '康复中'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='健康状态')),
                ('found_location', models.CharField(max_length=255, verbose_name='发现位置')),
                ('description', models.TextField(verbose_name='情况说明')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rescue_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approved_animal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='animals.animal', verbose_name='生成的动物档案')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rescue_requests', to='campuses.campus', verbose_name='所属校区')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rescue_requests', to='animals.animalcategory', verbose_name='动物分类')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rescue_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '救助申请',
                'verbose_name_plural': '救助申请',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RescueRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.animals.models.rescue_image_upload_to, verbose_name='图片')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('rescue_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.rescuerequest', verbose_name='救助申请')),
            ],
            options={
                'verbose_name': '救助申请图片',
                'verbose_name_plural': '救助申请图片',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.animals.models.animal_image_upload_to, verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='说明')),
                ('is_cover', models.BooleanField(default=False, verbose_name='封面图')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.animal', verbose_name='动物')),
            ],
            options={
                'verbose_name': '动物图片',
                'verbose_name_plural': '动物图片',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='animals.animalcategory', verbose_name='动物分类'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='animals', to='tags.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='rescuerequest',
            index=models.Index(fields=['status', '-created_at'], name='rescue_review_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['is_published', 'rescue_status', '-published_at'], name='animal_rescue_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['category', 'health_status', 'campus'], name='animal_filter_idx'),
        ),
    ]
