# Generated by Django 4.2.30 on 2026-06-22 06:14

import apps.animals.models
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='image',
            field=models.ImageField(upload_to=apps.animals.models.animal_image_upload_to, validators=[apps.core.validators.validate_image_size], verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='rescuerequestimage',
            name='image',
            field=models.ImageField(upload_to=apps.animals.models.rescue_image_upload_to, validators=[apps.core.validators.validate_image_size], verbose_name='图片'),
        ),
    ]
