# Generated by Django 4.2.30 on 2026-06-22 04:33

import apps.volunteers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='已隐藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '用户帖子',
                'verbose_name_plural': '用户帖子',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intention', models.TextField(verbose_name='志愿意愿')),
                ('skills', models.CharField(max_length=255, verbose_name='擅长技能')),
                ('availability', models.CharField(max_length=255, verbose_name='可服务时间')),
                ('experience', models.TextField(blank=True, verbose_name='相关经验')),
                ('material', models.FileField(blank=True, upload_to=apps.volunteers.models.volunteer_material_upload_to, verbose_name='申请材料')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_volunteer_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '志愿者申请',
                'verbose_name_plural': '志愿者申请',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=255, verbose_name='擅长技能')),
                ('availability', models.CharField(max_length=255, verbose_name='可服务时间')),
                ('bio', models.TextField(blank=True, verbose_name='志愿者简介')),
                ('status', models.CharField(choices=[('active', '有效'), ('inactive', '暂停')], default='active', max_length=20, verbose_name='状态')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('source_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='volunteers.volunteerapplication', verbose_name='来源申请')),
                ('tags', models.ManyToManyField(blank=True, related_name='volunteers', to='tags.tag', verbose_name='标签')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '志愿者档案',
                'verbose_name_plural': '志愿者档案',
                'ordering': ('-joined_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='举报原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('dismissed', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('pending_marker', models.BooleanField(default=True, editable=False, null=True)),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理说明')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='volunteers.communitypost', verbose_name='被举报帖子')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_reports', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '社区举报',
                'verbose_name_plural': '社区举报',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunityArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('summary', models.CharField(max_length=300, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('cover', models.ImageField(blank=True, upload_to=apps.volunteers.models.article_cover_upload_to, verbose_name='封面图')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tags', models.ManyToManyField(blank=True, related_name='community_articles', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '社区文章',
                'verbose_name_plural': '社区文章',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['status', '-created_at'], name='volunteer_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'post', 'pending_marker'), name='uniq_pending_reporter_post'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['is_hidden', '-created_at'], name='community_post_pub_idx'),
        ),
    ]
