# Generated by Django 4.2.30 on 2026-06-22 06:14

import apps.core.validators
import apps.volunteers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityarticle',
            name='cover',
            field=models.ImageField(blank=True, upload_to=apps.volunteers.models.article_cover_upload_to, validators=[apps.core.validators.validate_image_size], verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='material',
            field=models.FileField(blank=True, upload_to=apps.volunteers.models.volunteer_material_upload_to, validators=[apps.core.validators.validate_document_size], verbose_name='申请材料'),
        ),
    ]
