CREATE TABLE IF NOT EXISTS tags_tagcategory (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tags_tag (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  color VARCHAR(20) NOT NULL DEFAULT '#66793a',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uniq_tag_category_name UNIQUE (category_id, name),
  CONSTRAINT tags_tag_category_fk FOREIGN KEY (category_id) REFERENCES tags_tagcategory(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
