# Generated by Django 4.2.30 on 2026-06-22 05:00

import apps.posters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副标题')),
                ('image', models.ImageField(upload_to=apps.posters.models.poster_upload_to, verbose_name='海报图片')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='跳转链接')),
                ('page', models.CharField(choices=[('home', '首页'), ('rescue', '救助信息'), ('adoption', '领养中心'), ('volunteer', '志愿者社区'), ('donation', '爱心捐赠'), ('activity', '校园活动')], default='home', max_length=20, verbose_name='展示页面')),
                ('slot', models.CharField(choices=[('banner', 'Banner 轮播'), ('quick_entry', '金刚区入口'), ('module_card', '模块卡片'), ('public_welfare', '公益海报')], max_length=30, verbose_name='展示位')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='posters', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '海报',
                'verbose_name_plural': '海报',
                'ordering': ('sort_order', '-created_at'),
                'indexes': [models.Index(fields=['page', 'slot', 'is_active'], name='poster_position_idx')],
            },
        ),
    ]
