# Generated by Django 4.2.30 on 2026-06-22 06:14

import apps.core.validators
import apps.posters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(upload_to=apps.posters.models.poster_upload_to, validators=[apps.core.validators.validate_image_size], verbose_name='海报图片'),
        ),
    ]
