# Generated by Django 4.2.30 on 2026-06-22 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('campuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='活动名称')),
                ('summary', models.CharField(max_length=300, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='活动说明')),
                ('location', models.CharField(max_length=255, verbose_name='活动地点')),
                ('starts_at', models.DateTimeField(verbose_name='活动开始')),
                ('ends_at', models.DateTimeField(verbose_name='活动结束')),
                ('registration_starts_at', models.DateTimeField(verbose_name='报名开始')),
                ('registration_ends_at', models.DateTimeField(verbose_name='报名结束')),
                ('capacity', models.PositiveIntegerField(verbose_name='人数上限')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '报名中'), ('closed', '已关闭'), ('completed', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='campuses.campus', verbose_name='校区')),
                ('tags', models.ManyToManyField(blank=True, related_name='activities', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '校园活动',
                'verbose_name_plural': '校园活动',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', '已报名'), ('cancelled', '已取消')], default='registered', max_length=20, verbose_name='状态')),
                ('active_marker', models.BooleanField(default=True, editable=False, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='activities.activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_participations', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'ordering': ('-registered_at',),
                'indexes': [models.Index(fields=['activity', 'status'], name='activity_signup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('user', 'activity', 'active_marker'), name='uniq_active_activity_user'),
        ),
    ]
