# Generated by Django 4.2.30 on 2026-06-22 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('system', '系统'), ('rescue', '救助'), ('adoption', '领养'), ('volunteer', '志愿者'), ('report', '举报')], default='system', max_length=20, verbose_name='业务类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('related_app', models.CharField(blank=True, max_length=50, verbose_name='关联应用')),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notice_user_read_idx')],
            },
        ),
    ]
